
import os
output_path_in_container = "/sandbox/outputs/test_output_persistent/agent_generated_file.txt" # 直接拼接，确保正斜杠
output_dir_in_container = os.path.dirname(output_path_in_container)
print(f"Attempting to create directory: {output_dir_in_container}")
if not os.path.exists(output_dir_in_container):
    os.makedirs(output_dir_in_container, exist_ok=True)
    print(f"Directory {output_dir_in_container} created or already exists.")
else:
    print(f"Directory {output_dir_in_container} already exists.")
    print(f"Attempting to write file: {output_path_in_container}")
try:
    with open(output_path_in_container, "w") as f:
        f.write("Persistent log test: File generated by AI.")
    print(f"File '{output_path_in_container}' created successfully.")
except Exception as e:
    print(f"Error writing file {output_path_in_container}: {e}")
import traceback
print(traceback.format_exc())
