
import os
output_path = "/sandbox/outputs\test_output_persistent/agent_generated_file.txt"
output_dir = os.path.dirname(output_path)
if not os.path.exists(output_dir):
    os.makedirs(output_dir, exist_ok=True)
with open(output_path, "w") as f:
    f.write("Persistent log test: File generated by AI.")
print(f"File '{output_path}' created.")
